version: '3.6'
services:
  mermaidjs:
    build:
      context: build/mermaid-js
      dockerfile: Dockerfile
#  php-tools:
#    build:
#      context: .
#      dockerfile: build/php-tools/Dockerfile
#      args:
#        FROM_IMAGE: "ubuntu:${PHP_TOOLS_UBUNTU_VERSION}"
#    volumes:
#      - "/etc/passwd:/etc/passwd:ro"
#      - "/etc/group:/etc/group:ro"
#      - "/tmp:/tmp"
  chefdk-and-docker:
    build:
      context: .
      dockerfile: build/chefdkAndDocker/Dockerfile
      args:
        - CHEF_DK_VERSION=${CHEF_DK_VERSION}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: "host"
